# Generated by Django 4.2.16 on 2024-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chess_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChessPiece",
            fields=[
                (
                    "position",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("piece_unicode", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
