# Generated by Django 4.2.16 on 2024-10-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chess_app", "0003_board_delete_chesspiece"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="value",
            field=models.CharField(default="", max_length=255),
        ),
    ]
