# Generated by Django 4.2.16 on 2024-10-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chess_app", "0005_game_gamejournal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamejournal",
            name="game",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="GameJournal",
        ),
    ]
