# Generated by Django 4.2.16 on 2024-10-18 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Chess_app", "0009_game_moves_game_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="current_turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_turn",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="fen",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_player1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_player2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
