# Generated by Django 4.2.16 on 2024-10-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
