# Generated by Django 5.1.2 on 2024-10-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_delete_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='entry',
        ),
    ]
