# Generated by Django 4.2.16 on 2024-10-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Chess_app", "0010_alter_game_current_turn_alter_game_fen_and_more"),
        ("journal", "0003_remove_journalentry_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="game_id",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Chess_app.game",
            ),
        ),
    ]
